# матрицы

## Матрицы numpy

In [20]:
import numpy as np

### Создание

In [21]:
# создание массив - вектор
a = np.array([1, 2, 3, 4, 5, 6], dtype='float32')
print('Массив', a)
print('Размер', a.shape)
print('тип элементов',  a.dtype)

Массив [1. 2. 3. 4. 5. 6.]
Размер (6,)
тип элементов float32


In [22]:
# матрица
a = np.array([[1, 2, 3, 4, 5, 6],
              [3, 1, 5, 7, 4, 9],
              [1, 3, 1, 0, 4, 6]])
a

array([[1, 2, 3, 4, 5, 6],
       [3, 1, 5, 7, 4, 9],
       [1, 3, 1, 0, 4, 6]])

In [23]:
# общие данные по массиву

print(f'Размерность: {a.shape}')
print(f'Тип хранимых данных в массиве: {a.dtype}')
print(f'Тип объекта: {type(a)}')
print(f'Кол-во элементов массива: {a.size}')
print(f'Кол-во измерений: {a.ndim}')
print(f'размер в байтах: {a.nbytes}')

Размерность: (3, 6)
Тип хранимых данных в массиве: int64
Тип объекта: <class 'numpy.ndarray'>
Кол-во элементов массива: 18
Кол-во измерений: 2
размер в байтах: 144


In [24]:
# матрица нулей
b = np.zeros((3, 6))
b, b.shape

(array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 (3, 6))

In [25]:
# матрица единиц
b = np.ones((3, 6))
b, b.shape

(array([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]),
 (3, 6))

In [26]:
# создание матрицы единиц размерностью матрица "а"
b = np.ones_like(a)
b, b.shape

(array([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]),
 (3, 6))

In [27]:
# создание пустой матрицы (случайные элементы)
c = np.empty((3,6), dtype='int')
c

array([[4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4607182418800017408, 4607182418800017408]])

### Объединение матриц

In [28]:
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 4, 5, 6, 1, 1, 1, 1, 1, 1],
       [3, 1, 5, 7, 4, 9, 1, 1, 1, 1, 1, 1],
       [1, 3, 1, 0, 4, 6, 1, 1, 1, 1, 1, 1]])

In [29]:
np.concatenate((a, b), axis=0)

array([[1, 2, 3, 4, 5, 6],
       [3, 1, 5, 7, 4, 9],
       [1, 3, 1, 0, 4, 6],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [30]:
np.vstack((a,b))

array([[1, 2, 3, 4, 5, 6],
       [3, 1, 5, 7, 4, 9],
       [1, 3, 1, 0, 4, 6],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [31]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 6, 1, 1, 1, 1, 1, 1],
       [3, 1, 5, 7, 4, 9, 1, 1, 1, 1, 1, 1],
       [1, 3, 1, 0, 4, 6, 1, 1, 1, 1, 1, 1]])

### Удаление данных из массива

In [32]:
a = np.random.randint(1,100,size=(2,3))
a, a.shape

(array([[ 4, 63, 54],
        [90, 75, 26]]),
 (2, 3))

In [33]:
a2 = a[:,:2]
a2

array([[ 4, 63],
       [90, 75]])

In [34]:
del a
a2,a2.shape

(array([[ 4, 63],
        [90, 75]]),
 (2, 2))

In [35]:
a = np.random.randint(1,100,size=(2,3))
a, a.shape

(array([[13, 18, 50],
        [91,  3, 26]]),
 (2, 3))

In [36]:
np.delete(a,1,axis=1).shape, np.delete(a,1,axis=1)

((2, 2),
 array([[13, 50],
        [91, 26]]))

In [37]:
np.delete(a,0,axis=1).shape, np.delete(a,0,axis=1)

((2, 2),
 array([[18, 50],
        [ 3, 26]]))

In [38]:
np.delete(a,0,axis=0).shape, np.delete(a,0,axis=0)

((1, 3), array([[91,  3, 26]]))

### Индексация

In [39]:
m = np.array([
    [20, 1, 3],
    [46, 6, 7],
    [101, -1, 36],
    [32, 71, 5]
    ])

In [40]:
print(m[0, 2])
print(m[1, 2])
print(m[2, 0])

3
7
101


Чтобы вывести целую строку, второй параметр нужно заменить на :.   
Чтобы вывести целый столбец, первый параметр нужно заменить на :.  
В данном случае это означает «взять все значения».

In [41]:
m[:,1]

array([ 1,  6, -1, 71])

### Арифметические операции

In [42]:
print('a=',a)
b = np.random.randint(1,100,size=(2,3))
print('b=', b)

a= [[13 18 50]
 [91  3 26]]
b= [[14 97 93]
 [44 67 70]]


In [43]:
a + b

array([[ 27, 115, 143],
       [135,  70,  96]])

In [44]:
a * b

array([[ 182, 1746, 4650],
       [4004,  201, 1820]])

In [45]:
a - b

array([[ -1, -79, -43],
       [ 47, -64, -44]])

### Умножение матриц

матричное умножения между двумя a и b.  

должны быть совместимыми по форме, то есть  

Если a имеет форму (m, n), а b имеет форму (n, p), то результат будет массивом формы (m, p).  

In [46]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [47]:
# оператор матричного умножения,  Работает с объектами поддерживающими матричное умножение (например numpy )
a @ b

array([[22, 28],
       [49, 64]])

In [48]:
# a.dot(b) — это метод объекта a, работает только с numpy массивами
a.dot(b)

array([[22, 28],
       [49, 64]])

In [49]:
# np.dot(a, b) — функция из модуля NumPy (работает с любыми объектами которые можно преобразовать в numpy массивы)
np.dot(a,b)

array([[22, 28],
       [49, 64]])

### Ранг матрицы 

Ранг матрицы - это максимальное количество линейно независимых строк (или столбцов) в матрице.

In [50]:
a = np.random.randint(1,10,size=(3,3))
a

array([[6, 5, 2],
       [2, 9, 3],
       [9, 2, 1]])

In [51]:
np.linalg.matrix_rank(a)

np.int64(3)

### Транспонирование

In [52]:
a = np.random.randint(1,10,size=(2,5))
a

array([[2, 6, 6, 4, 6],
       [9, 1, 2, 1, 8]])

In [53]:

a.T

array([[2, 9],
       [6, 1],
       [6, 2],
       [4, 1],
       [6, 8]])

In [54]:
np.transpose(a)

array([[2, 9],
       [6, 1],
       [6, 2],
       [4, 1],
       [6, 8]])

### Обратная матрица  
Обратная матрица — это такая квадратная матрица , которая при умножении на исходную матрицу даёт единичную матрицу E:

In [55]:
a = np.random.randint(1,10,size=(3,3))
a

array([[2, 4, 6],
       [5, 9, 7],
       [9, 2, 8]])

In [56]:
# вычисляем обратную матрицу
a_inv = np.linalg.inv(a)
a_inv

array([[-0.26605505,  0.09174312,  0.11926606],
       [-0.10550459,  0.17431193, -0.0733945 ],
       [ 0.32568807, -0.14678899,  0.00917431]])

## Матрицы Pytorch (Тензоры)

`Тензор (tensor)` - это математический и абстрактный объект, который обобщает понятия скаляра, вектора и матрицы.   

**Основные характеристики тензоров:**  

- `Ранг:` Ранг тензора определяет, сколько индексов ему требуется для полной спецификации. Скаляр (тензор нулевого ранга) не требует индексов, вектор (тензор первого   ранга) требует один индекс, матрица (тензор второго ранга) - два индекса, и так далее.  
  
- `Размерности:` Тензоры имеют размерности, которые определяют, сколько элементов содержится вдоль каждой из их осей.  

- `Компоненты:` Элементы тензора называются его компонентами. Компоненты тензора могут быть числами, функциями или другими объектами в зависимости от контекста.  


In [57]:
import torch

# создаем тензор ранга 3 размером 2x2x2 со случайными значениями
tensor_torch = torch.ones(2, 2, 2)

# Выводим созданный тензор
print(tensor_torch)

# Определяем объем памяти, занимаемый тензором в байтах
memory_bytes_torch = tensor_torch.element_size() * tensor_torch.nelement()


import numpy as np

# Создаем тензор ранга 3 размером 2x2x2 со случайными значениями
tensor_numpy = np.ones((2, 2, 2))

# Выводим созданный тензор
print(tensor_numpy)


# Определяем объем памяти, занимаемый массивом в байтах
memory_bytes_numpy = tensor_numpy.nbytes


# Выводим объем памяти
print(f"Объем памяти, занимаемый массивом: {memory_bytes_numpy} байт")

print(f"Объем памяти, занимаемый тензором: {memory_bytes_torch} байт")

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
Объем памяти, занимаемый массивом: 64 байт
Объем памяти, занимаемый тензором: 32 байт


###  Операции

In [58]:
a = torch.randn(2, 2)
a

tensor([[-1.4437,  1.5997],
        [ 0.3603, -0.2474]])

In [59]:
# Среднее по оси
torch.mean(a, 0)

tensor([-0.5417,  0.6762])

In [60]:
# Среднее по тензору
torch.mean(a)

tensor(0.0672)

In [61]:
# матричное умножение
a @ a

tensor([[ 2.6608, -2.7053],
        [-0.6093,  0.6376]])

In [62]:
x= torch.tensor([[2,3,4],[5,6,7]])
y= torch.tensor([[1,3],[1,1], [1,1]])

x @ y

tensor([[ 9, 13],
        [18, 28]])

In [64]:
# поэлементное умножение
x= torch.tensor([[2,3],[5,6]])
y= torch.tensor([[1,3],[1,1]])

print('x= \n', x)
print('y= \n', y)
print('product = \n', x * y)

x= 
 tensor([[2, 3],
        [5, 6]])
y= 
 tensor([[1, 3],
        [1, 1]])
product = 
 tensor([[2, 9],
        [5, 6]])


In [44]:
# транспонирование
x.transpose(1, 0)

tensor([[2, 5],
        [3, 6]])

In [45]:
x = torch.rand(2, 3, 2)
x

tensor([[[0.8392, 0.8937],
         [0.1047, 0.6420],
         [0.1188, 0.5488]],

        [[0.0640, 0.6889],
         [0.0699, 0.3821],
         [0.8785, 0.6589]]])

In [46]:
x.transpose(1, 0)

tensor([[[0.8392, 0.8937],
         [0.0640, 0.6889]],

        [[0.1047, 0.6420],
         [0.0699, 0.3821]],

        [[0.1188, 0.5488],
         [0.8785, 0.6589]]])

In [47]:
%%time
# Создаем батч матриц (трехмерные тензоры)
batch_A = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
batch_B = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# Выполняем пакетное матричное умножение
result = torch.bmm(batch_A, batch_B)

result

CPU times: user 790 μs, sys: 60 μs, total: 850 μs
Wall time: 798 μs


tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])

In [48]:
%%time
# Создаем батч матриц (трехмерные тензоры)
batch_A = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
batch_B = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# Выполняем пакетное матричное умножение
result = torch.matmul(batch_A, batch_B)

result

CPU times: user 448 μs, sys: 32 μs, total: 480 μs
Wall time: 587 μs


tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])

## Разреженные матрицы

In [1]:
import numpy as np 
import sys
from scipy.sparse import csr_matrix  

### Создание

In [2]:


# Определяем ненулевые элементы и их координаты
data = np.array([1, 5, 8, 3, 6, 4, 7])
row_indices = np.array([0, 1, 1, 2, 2, 4, 4])
col_indices = np.array([3, 0, 1, 2, 4, 1, 3])

# Создаем CSR матрицу
csr = csr_matrix((data, (row_indices, col_indices)), shape=(5, 5))

# Печатаем матрицу в плотном виде для наглядности
print("Матрица в плотном формате:")
print(csr.toarray())

# Выводим компоненты CSR
print("\nКомпоненты CSR:")
print("data:", csr.data)        # ненулевые элементы
print("indices:", csr.indices)  # индексы столбцов
print("indptr:", csr.indptr)    # указатели на начало строки

Матрица в плотном формате:
[[0 0 0 1 0]
 [5 8 0 0 0]
 [0 0 3 0 6]
 [0 0 0 0 0]
 [0 4 0 7 0]]

Компоненты CSR:
data: [1 5 8 3 6 4 7]
indices: [3 0 1 2 4 1 3]
indptr: [0 1 3 5 5 7]


### умножение матрицы на вектор

In [3]:
import numpy as np
from scipy.sparse import csr_matrix

# Определяем ненулевые элементы и их координаты - Создаем разряженную матрицу 4x5
data = np.array([1, 2, 3, 4])
row_indices = np.array([0, 1, 2, 3])
col_indices = np.array([0, 2, 3, 1])

# Создаем разряженную матрицу в формате CSR
sparse_matrix = csr_matrix((data, (row_indices, col_indices)), shape=(4, 5))

# Выводим разряженную матрицу
print("Разряженная матрица:")
print(sparse_matrix)

# Конвертируем в плотную матрицу для наглядности
dense_matrix = sparse_matrix.toarray()
print("\nПлотная матрица:")
print(dense_matrix)

# Пример умножения разряженной матрицы на плотную матрицу
dense_vector = np.array([[1], [2], [3], [4], [5]])
result = sparse_matrix.dot(dense_vector)

print("\nРезультат умножения разряженной матрицы на вектор:")
print(result)


Разряженная матрица:
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (4, 5)>
  Coords	Values
  (0, 0)	1
  (1, 2)	2
  (2, 3)	3
  (3, 1)	4

Плотная матрица:
[[1 0 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 4 0 0 0]]

Результат умножения разряженной матрицы на вектор:
[[ 1]
 [ 6]
 [12]
 [ 8]]


In [4]:
from sklearn.feature_extraction.text import CountVectorizer

# Пример документов
documents = [
    "Это первый документ.",
    "Это второй документ.",
    "И это третий документ."
]

# Создание разряженной матрицы с помощью CountVectorizer
vectorizer = CountVectorizer()
sparse_matrix = vectorizer.fit_transform(documents)

# Выводим разряженную матрицу
print("Разряженная матрица (формат CSR):")
print(sparse_matrix)

# Конвертируем в плотную матрицу для наглядности
dense_matrix = sparse_matrix.toarray()
print("\nПлотная матрица:")
print(dense_matrix)

# Показываем имена признаков
print("\nПризнаки:")
print(vectorizer.get_feature_names_out())

Разряженная матрица (формат CSR):
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 5)>
  Coords	Values
  (0, 4)	1
  (0, 2)	1
  (0, 1)	1
  (1, 4)	1
  (1, 1)	1
  (1, 0)	1
  (2, 4)	1
  (2, 1)	1
  (2, 3)	1

Плотная матрица:
[[0 1 1 0 1]
 [1 1 0 0 1]
 [0 1 0 1 1]]

Признаки:
['второй' 'документ' 'первый' 'третий' 'это']
